/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrentalsystem;

import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author saipa
 */
public class Cars extends javax.swing.JFrame {

    /**
     * Creates new form Cars
     */
    public Cars() {
        initComponents();
        autoID();
        table_update();
    }
    
    Connection con;
    PreparedStatement pst;
    
    private void clearFields() {
        
        txtRegnum.setText(null);
        txtBrand.setText(null);
        txtModel.setText(null);
        comStatus.setSelectedIndex(-1);
        txtPrice.setText("");
        txtBrand.requestFocus();
        autoID();
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        toCarrental = new javax.swing.JButton();
        toReturncar = new javax.swing.JButton();
        toCustomer = new javax.swing.JButton();
        toHome = new javax.swing.JButton();
        toPayment = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtRegnum = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        comStatus = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        btnSave5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnSave5.setForeground(new java.awt.Color(255, 0, 51));
        btnSave5.setText("Home");
        btnSave5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave5ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 0, 51));

        toCarrental.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        toCarrental.setForeground(new java.awt.Color(255, 0, 51));
        toCarrental.setText("Car Rental");
        toCarrental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toCarrentalActionPerformed(evt);
            }
        });

        toReturncar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        toReturncar.setForeground(new java.awt.Color(255, 0, 51));
        toReturncar.setText("Return Car");
        toReturncar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toReturncarActionPerformed(evt);
            }
        });

        toCustomer.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        toCustomer.setForeground(new java.awt.Color(255, 0, 51));
        toCustomer.setText("Customer");
        toCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toCustomerActionPerformed(evt);
            }
        });

        toHome.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        toHome.setForeground(new java.awt.Color(255, 0, 51));
        toHome.setText("Home");
        toHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toHomeActionPerformed(evt);
            }
        });

        toPayment.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        toPayment.setForeground(new java.awt.Color(255, 0, 51));
        toPayment.setText("Payment");
        toPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toPaymentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(toReturncar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toCarrental, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toPayment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(toCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(toCarrental, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(toReturncar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(toPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(toHome, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 846, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 0, 51));
        jLabel15.setText("Cars List");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 230, -1, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 51));
        jLabel16.setText("Registration Num");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 93, -1, -1));

        txtRegnum.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtRegnum.setForeground(new java.awt.Color(204, 0, 51));
        getContentPane().add(txtRegnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 121, 135, 31));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 0, 51));
        jLabel17.setText("Brand");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 93, 167, -1));

        txtBrand.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtBrand.setForeground(new java.awt.Color(204, 0, 51));
        getContentPane().add(txtBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 121, 167, 31));

        txtModel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtModel.setForeground(new java.awt.Color(204, 0, 51));
        getContentPane().add(txtModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 121, 167, 31));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 0, 51));
        jLabel18.setText("Status");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(752, 99, 96, -1));

        txtPrice.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtPrice.setForeground(new java.awt.Color(204, 0, 51));
        getContentPane().add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(876, 121, 155, 31));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 0, 51));
        jLabel19.setText("Price");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(876, 99, 167, -1));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 0, 51));
        jLabel20.setText("Model");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 99, 167, -1));

        comStatus.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        comStatus.setForeground(new java.awt.Color(204, 0, 51));
        comStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Booked", "Available" }));
        comStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comStatusActionPerformed(evt);
            }
        });
        getContentPane().add(comStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(752, 121, 106, 31));

        btnSave.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 0, 51));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 170, 121, 34));

        btnEdit.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 0, 51));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 170, 121, 34));

        btnDelete.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 0, 51));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 170, 121, 34));

        btnReset.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 0, 51));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(752, 170, 121, 34));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 0, 51));
        jLabel21.setText("Manage Cars");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 52, -1, -1));

        jTable1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Registration", "Brand", "Model", "Status", "Price"
            }
        ));
        jTable1.setRowHeight(25);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 276, 851, 259));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    public void table_update() {
        try {
            int c;
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/carrental","root","");
            pst = con.prepareStatement("select * from car");
            ResultSet Rs = pst.executeQuery();
            ResultSetMetaData rd = Rs.getMetaData();
            c=rd.getColumnCount();
            DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
            df.setRowCount(0);
            
            while(Rs.next())
            {
              Vector v2 = new Vector();
              for(int i=1; i<=c; i++)
              {
                  v2.add(Rs.getInt("reg_num"));
                  v2.add(Rs.getString("brand"));
                  v2.add(Rs.getString("model"));
                  v2.add(Rs.getString("status"));
                  v2.add(Rs.getInt("price"));
              }
              df.addRow(v2);
            
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Cars.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Cars.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    
    
    
    
    
    
    public void autoID(){
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
        
            con = DriverManager.getConnection("jdbc:mysql://localhost/carrental","root","");
            Statement s = con.createStatement();
            
            ResultSet rs = s.executeQuery("select Max(reg_num)from car");
            rs.next();
            rs.getString("Max(reg_num)");
            
            if(rs.getString("Max(reg_num)")==null){
                txtRegnum.setText("0001");
            }
            else
            {
                long id = Long.parseLong(rs.getString("Max(reg_num)"));
                id++;
                
                txtRegnum.setText("0" + String.format("%03d", id));
            }
            
    }   
            catch (ClassNotFoundException ex) {
            Logger.getLogger(Cars.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Cars.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
    }
    
    
    
    
    private void comStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comStatusActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
           // TODO add your handling code here:
            String rgno = txtRegnum.getText();
            String brand = txtBrand.getText();
            String mod = txtModel.getText();
            String aval = comStatus.getSelectedItem().toString();
           try {   
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/carrental","root","");
            pst = con.prepareStatement("insert into car(reg_num,brand,status,price,model) values(?,?,?,?,?)");
            pst.setInt(1, Integer.parseInt(rgno));
            pst.setString(2, brand);
            pst.setString(3, aval);
            pst.setInt(4, Integer.parseInt(txtPrice.getText()));
            pst.setString(5, mod);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Car added successfully");
            txtBrand.setText("");
            txtModel.setText("");
            comStatus.setSelectedIndex(-1);
            txtPrice.setText("");
            txtBrand.requestFocus();
            autoID();
            table_update();
            con.close();}
          catch (ClassNotFoundException ex) {
            Logger.getLogger(Cars.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Cars.class.getName()).log(Level.SEVERE, null, ex);
        }
    
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel d1 = (DefaultTableModel)jTable1.getModel();
        int selectIndex = jTable1.getSelectedRow();
        
        txtRegnum.setText(d1.getValueAt(selectIndex,0).toString());
        txtBrand.setText(d1.getValueAt(selectIndex,1).toString());
        txtModel.setText(d1.getValueAt(selectIndex,2).toString());
        comStatus.setSelectedItem(d1.getValueAt(selectIndex,3).toString());
        txtPrice.setText(d1.getValueAt(selectIndex,4).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
            DefaultTableModel d1 = (DefaultTableModel)jTable1.getModel();
            int selectIndex = jTable1.getSelectedRow();
            try {    
            String id = d1.getValueAt(selectIndex, 0).toString();
            String brand = txtBrand.getText();
            String model = txtModel.getText();
            String status = comStatus.getSelectedItem().toString();
            int price = Integer.parseInt(txtPrice.getText());
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/carrental","root","");
            pst = con.prepareStatement("update car set brand=?,model=?,status=?,price=? where reg_num=?");
            
            pst.setString(1,brand);
            pst.setString(2,model);
            pst.setString(3,status);
            pst.setInt(4,price);
            pst.setString(5,id);
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Record updated");
            table_update();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Cars.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Cars.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
         DefaultTableModel d1 = (DefaultTableModel)jTable1.getModel();
            int selectIndex = jTable1.getSelectedRow();    
            
            String id = d1.getValueAt(selectIndex, 0).toString();
            
           int dialogResult = JOptionPane.showConfirmDialog(this,"Do you want to delete the record","warning",JOptionPane.YES_NO_OPTION);
           if(dialogResult == JOptionPane.YES_OPTION)
           {
             try {
                 Class.forName("com.mysql.jdbc.Driver");
                 con = DriverManager.getConnection("jdbc:mysql://localhost/carrental","root","");
                 
                 pst = con.prepareStatement("delete from car where reg_num=?");
                 
                 pst.setString(1,id);
                 pst.executeUpdate();
                 
                 JOptionPane.showMessageDialog(this,"Record Deleted");
                 
                 table_update();
             } catch (ClassNotFoundException ex) {
                 Logger.getLogger(Cars.class.getName()).log(Level.SEVERE, null, ex);
             } catch (SQLException ex) {
                 Logger.getLogger(Cars.class.getName()).log(Level.SEVERE, null, ex);
             }
           }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_btnResetActionPerformed

    private void toCarrentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toCarrentalActionPerformed
        // TODO add your handling code here:
        Rents r =new Rents();
        r.setVisible(true);
        dispose();
    }//GEN-LAST:event_toCarrentalActionPerformed

    private void toReturncarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toReturncarActionPerformed
        // TODO add your handling code here:
        Returns ret =new Returns();
        ret.setVisible(true);
        dispose();
    }//GEN-LAST:event_toReturncarActionPerformed

    private void toCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toCustomerActionPerformed
        // TODO add your handling code here:
        Customers c =new Customers();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_toCustomerActionPerformed

    private void toHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toHomeActionPerformed
        // TODO add your handling code here:
        Main m =new Main();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_toHomeActionPerformed

    private void btnSave5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSave5ActionPerformed

    private void toPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toPaymentActionPerformed
        // TODO add your handling code here:
        Payment p =new Payment();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_toPaymentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cars().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSave5;
    private javax.swing.JComboBox<String> comStatus;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton toCarrental;
    private javax.swing.JButton toCustomer;
    private javax.swing.JButton toHome;
    private javax.swing.JButton toPayment;
    private javax.swing.JButton toReturncar;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtRegnum;
    // End of variables declaration//GEN-END:variables
}
