/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrentalsystem;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.time.format.DateTimeFormatter;  
import java.time.LocalDateTime;   
import java.util.Date;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.awt.print.Printable;
/**
 *
 * @author saipa
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
        autoID();
        


    }
    
    Connection con;
    PreparedStatement pst;
    PreparedStatement pst1;
    PreparedStatement pst2;
    ResultSet rs;
    
    private void clearFields() {
        
        
        
        txtpaymentid.setText(null);
        
        
        txtcustid.setText("");
        txtfees.setText("");
        txtfine.setText("");
        txtpaymentdate.setText("");
        txtarea.setText("");
        txtcustid.requestFocus();
        autoID();
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        toCustomer = new javax.swing.JButton();
        toCarrental = new javax.swing.JButton();
        toCar = new javax.swing.JButton();
        toHome = new javax.swing.JButton();
        toReturncar = new javax.swing.JButton();
        toFeedback = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtcustid = new javax.swing.JTextField();
        txtfine = new javax.swing.JTextField();
        txtfees = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        btngenreceipt = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        txtpaymentid = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtarea = new java.awt.TextArea();
        btnprintreceipt = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        txtpaymentdate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 0, 51));

        toCustomer.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        toCustomer.setForeground(new java.awt.Color(255, 0, 51));
        toCustomer.setText("Customers");
        toCustomer.setActionCommand("");
        toCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toCustomerActionPerformed(evt);
            }
        });

        toCarrental.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        toCarrental.setForeground(new java.awt.Color(255, 0, 51));
        toCarrental.setText("Car Rental");
        toCarrental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toCarrentalActionPerformed(evt);
            }
        });

        toCar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        toCar.setForeground(new java.awt.Color(255, 0, 51));
        toCar.setText("Cars");
        toCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toCarActionPerformed(evt);
            }
        });

        toHome.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        toHome.setForeground(new java.awt.Color(255, 0, 51));
        toHome.setText("Home");
        toHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toHomeActionPerformed(evt);
            }
        });

        toReturncar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        toReturncar.setForeground(new java.awt.Color(255, 0, 51));
        toReturncar.setText("Return Car");
        toReturncar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toReturncarActionPerformed(evt);
            }
        });

        toFeedback.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        toFeedback.setForeground(new java.awt.Color(255, 0, 51));
        toFeedback.setText("Feedback");
        toFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toFeedbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(toCarrental, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toReturncar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toFeedback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(toCar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(toCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(toCarrental, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(toReturncar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(toFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(toHome, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        txtcustid.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtcustid.setForeground(new java.awt.Color(204, 0, 51));
        txtcustid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcustidActionPerformed(evt);
            }
        });
        txtcustid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcustidKeyPressed(evt);
            }
        });

        txtfine.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtfine.setForeground(new java.awt.Color(204, 0, 51));

        txtfees.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtfees.setForeground(new java.awt.Color(204, 0, 51));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 0, 51));
        jLabel20.setText("Customer Id");

        btngenreceipt.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btngenreceipt.setForeground(new java.awt.Color(255, 0, 51));
        btngenreceipt.setText("Generate receipt");
        btngenreceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenreceiptActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 51));
        jLabel16.setText("Payment Id");

        btnReset.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 0, 51));
        btnReset.setText("Reset");
        btnReset.setPreferredSize(new java.awt.Dimension(183, 31));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 0, 51));
        jLabel22.setText("Fees");

        txtpaymentid.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtpaymentid.setForeground(new java.awt.Color(204, 0, 51));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 0, 51));
        jLabel21.setText("Payment");

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 0, 51));
        jLabel19.setText("Fine");

        txtarea.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        btnprintreceipt.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnprintreceipt.setForeground(new java.awt.Color(255, 0, 51));
        btnprintreceipt.setText("Print receipt");
        btnprintreceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintreceiptActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 0, 51));
        jLabel23.setText("Payment date");

        txtpaymentdate.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtpaymentdate.setForeground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(btngenreceipt)
                                .addGap(32, 32, 32)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btnprintreceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtpaymentid, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcustid, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtfees, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtfine, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtpaymentdate, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(318, 318, 318)
                                .addComponent(jLabel21))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(txtarea, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(15, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel16)
                            .addComponent(jLabel22)))
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcustid, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpaymentid, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfine, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfees, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpaymentdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btngenreceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnprintreceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(txtarea, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void autoID(){
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
        
            con = DriverManager.getConnection("jdbc:mysql://localhost/carrental","root","");
            Statement s = con.createStatement();
            
            rs = s.executeQuery("select Max(payment_id)from payment");
            rs.next();
            rs.getString("Max(payment_id)");
            
            if(rs.getString("Max(payment_id)")==null){
                txtpaymentid.setText("4000");
            }
            else
            {
                long id = Long.parseLong(rs.getString("Max(payment_id)"));
                id++;
                
                txtpaymentid.setText(String.format("%03d", id));
            }
            
    }   
            catch (ClassNotFoundException ex) {
            Logger.getLogger(Cars.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Cars.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
    }
    
    
    private void toCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toCustomerActionPerformed
        // TODO add your handling code here:
        Customers cust =new Customers();
        cust.setVisible(true);
        dispose();
    }//GEN-LAST:event_toCustomerActionPerformed

    private void toCarrentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toCarrentalActionPerformed
        // TODO add your handling code here:
        Rents r =new Rents();
        r.setVisible(true);
        dispose();
    }//GEN-LAST:event_toCarrentalActionPerformed

    private void toCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toCarActionPerformed
        // TODO add your handling code here:
        Cars c =new Cars();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_toCarActionPerformed

    private void toHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toHomeActionPerformed
        // TODO add your handling code here:
        Main m =new Main();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_toHomeActionPerformed

    private void toReturncarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toReturncarActionPerformed
        // TODO add your handling code here:
        Returns ret =new Returns();
        ret.setVisible(true);
        dispose();
    }//GEN-LAST:event_toReturncarActionPerformed

    private void txtcustidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcustidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcustidActionPerformed

    private void btngenreceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenreceiptActionPerformed
        
        int payment_id = Integer.parseInt(txtpaymentid.getText());  
        
            int cust_id = Integer.parseInt(txtcustid.getText());
            String date = txtpaymentdate.getText();
            int fees = Integer.parseInt(txtfees.getText());
            int fine = Integer.parseInt(txtfine.getText());
            
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/carrental","root","");
            pst = con.prepareStatement("insert into payment(payment_id,customer_id,total_amt,fine,payment_date)values(?,?,?,?,?)");
            pst.setInt(1,payment_id);
            pst.setInt(2,cust_id);
            pst.setInt(3, fees);
            pst.setInt(4, fine);
            pst.setString(5, date);
           
            
            pst.executeUpdate();
            
            
            autoID();
            
        }
        catch (ClassNotFoundException ex) {
            Logger.getLogger(Returns.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Returns.class.getName()).log(Level.SEVERE, null, ex);
        }
             
        
        
        
        txtarea.setText(txtarea.getText()+"                                                                       Receipt                                                       \n\n\n");
       
        int firstnum = Integer.parseInt(txtfees.getText());
        int secondnum = Integer.parseInt(txtfine.getText());
        int total = firstnum+secondnum;
        txtarea.setText(txtarea.getText()+"Payment ID : "+txtpaymentid.getText()+"\n\n\n");
        txtarea.setText(txtarea.getText()+"Customer ID : "+txtcustid.getText()+"\n\n\n");
        txtarea.setText(txtarea.getText()+"Total amount paid : "+total+"\n\n\n");
        txtarea.setText(txtarea.getText()+"Payment date : "+txtpaymentdate.getText()+"\n\n\n");
        txtarea.setText(txtarea.getText()+"\n\n                                                                                                                               Signature\n");
        JOptionPane.showMessageDialog(this,"Success! Please provide your valuable feedback!");
    }//GEN-LAST:event_btngenreceiptActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        clearFields();
        

    }//GEN-LAST:event_btnResetActionPerformed

    private void btnprintreceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintreceiptActionPerformed
        // TODO add your handling code here:
            String printData = txtarea.getText();
            PrinterJob job = PrinterJob.getPrinterJob();
            boolean doPrint = job.printDialog();
        if (doPrint){
        try{
            job.print();
        }
        catch(Exception e){
            
        }
        }
    }//GEN-LAST:event_btnprintreceiptActionPerformed

    private void txtcustidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcustidKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            String cust_id = txtcustid.getText();
        
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                    con = DriverManager.getConnection("jdbc:mysql://localhost/carrental","root","");  
                    
                    pst1 = con.prepareStatement("select * from returns where customer_id=?");
                    pst1.setInt(1,Integer.parseInt(cust_id));
                    rs = pst1.executeQuery();
                    
                   
                    
                    if(rs.next()==false){
                JOptionPane.showMessageDialog(this,"Customer did not return the car");
            }
            else
            {
                String custfee = rs.getString("fees");
                txtfees.setText(custfee.trim());
                
                String custfine = rs.getString("fine");
                txtfine.setText(custfine.trim());
                
                DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
                Date date = new Date();
                
                txtpaymentdate.setText(dateFormat.format(date));
                
            }
                    
                    
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Rents.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Rents.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            
            
            }
        
        
                
    }//GEN-LAST:event_txtcustidKeyPressed

    private void toFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toFeedbackActionPerformed
        // TODO add your handling code here:
        Feedback f =new Feedback();
        f.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_toFeedbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btngenreceipt;
    private javax.swing.JButton btnprintreceipt;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton toCar;
    private javax.swing.JButton toCarrental;
    private javax.swing.JButton toCustomer;
    private javax.swing.JButton toFeedback;
    private javax.swing.JButton toHome;
    private javax.swing.JButton toReturncar;
    private java.awt.TextArea txtarea;
    private javax.swing.JTextField txtcustid;
    private javax.swing.JTextField txtfees;
    private javax.swing.JTextField txtfine;
    private javax.swing.JTextField txtpaymentdate;
    private javax.swing.JTextField txtpaymentid;
    // End of variables declaration//GEN-END:variables
}
